---
title: "Using demoR with Code Chunks"
author: "Kelly Bodwin"
output: html_document
---

```{r}
library(demoR)
```







```{r, include = FALSE}
library(tidyverse)
library(knitr)

hook_chunk <- knit_hooks$get('chunk')

knit_hooks$set(chunk = function(x, options) {
  if (!is.null(options$demo)) {
    assign(options$demo, x, envir = .GlobalEnv)
  } 
  
  hook_chunk(x, options)
})
```

```{r, demo = "how_to_plot2", include = FALSE}

thing <-              1:10

    plot(thing)  #commenting
    
    
#I am a comment

```

What the first chunk looks like:

````

```{r, include = FALSE, demo = "how_to_plot"}`r ''`

thing <-              1:10

    plot(thing)  #commenting
    
    
#I am a comment

```

````


What the second chunk looks like:
````

```{r, echo = FALSE}`r ''`

create_demo("how_to_plot") %>% 
  hlt_funs() %>% 
  hlt_regexp("#[^\n]*")
```

````

Knitted Output:

```{r, echo = FALSE}
bob <- create_demo("how_to_plot2") %>% 
  hlt_funs() %>% 
  hlt_regexp("#[^\n]*")
```


There is also a direct-from-string option, which is a good way to demonstrate broken code:

```{r, error = TRUE}
demo_code('

thing <- 1:10

plot(thing

') %>% hlt_funs()
```



