---
title: "Lab Exercise: Categorical Variables"
output: learnr::tutorial
tutorial:
  id: "Lab_catvars"
  version: 2.0
runtime: shiny_prerendered
---

```{r setup, include=FALSE}

if(file.exists("Lab_Exercise_CatVars2.html")){
  file.remove("Lab_Exercise_CatVars2.html")
}

sapply(list.files("./R/", full.names = TRUE), source)

require(learnr)
require(ggplot2)
require(dplyr)
require(shiny)
require(tidyr)
require(httpuv)
require(rlang)
require(glue)

knitr::opts_chunk$set(echo = FALSE)


source("https://raw.githubusercontent.com/kbodwin/ShinyLabs/master/Scripts/makeStrings.R")

correct <- "<font color='red'>Correct!</font><br><br>"
incorrect <- "<font color='red'>Not quite right...</font><br><br>"
congrats <- "<font color='red'>You did it!</font><br><br>"

titanic = read.csv('https://raw.githubusercontent.com/kbodwin/ShinyLabs/master/Datasets/titanic.csv')

titanic <- titanic %>% mutate(
  Survived = factor(Survived)
)

titanic_full <- titanic %>% mutate(
   Family.Aboard = Siblings.Spouses.Aboard + Parents.Children.Aboard,
   Passenger.Class = factor(Pclass, 
                           levels = c(1,2,3), 
                           labels = c("First", "Second", "Third"))
)

### %ni = new input (red), %oi = old input (blue)
```

```{r, echo=FALSE}
textInput("plot_var_1", 
          "What variable would you like to plot?", 
          value = " ", 
          width = '80%', 
          placeholder = NULL)

textInput("plot_dat_1", 
          "What dataset is that variable found in?", 
          value = " ", 
          width = '80%', 
          placeholder = NULL)

radioButtons("plot_type_1",
             "Would you like a barplot or a dotplot?",
             choices = c("barplot" = "geom_bar",
                         "dotplot" = "geom_dotplot"))


htmlOutput("code_4_1")

plotOutput("plot_4_1")
```


```{r, context="server"}


br_1 <- reactive(
  bridge("ggplot({dat}, aes(x = {var})) + {type}()",
       user_inputs = list(dat = "titanic_full", 
                          var = input$plot_var_1,
                          type = input$plot_type_1)
  )
)

output$code_4_1 <- renderText(expr_name(br_1()))
output$plot_4_1 <- renderPlot(eval(br_1()))

```
